loader:
  url: "https://test-service.ru/search-service/load"
  # ???????? ????????? Authorization ??????? (??? ? curl). ????? ? "Bearer ..." ??? ??? ? ???????????? ??? ????.
  authorizationHeaderValue: ""
  inputFile: "ids.txt"
  batchSize: 1000
  connectTimeoutMs: 5000
  readTimeoutMs: 30000